title: Title
author: Rebecca
email: abc@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Bom bom bom~

# social links
twitter_username: twitter # DO NOT include the @ character, or else the build will fail!
github_username:  leelacceber # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
